### ISSUE TITLE
Error parsing time stamp

### ISSUE THREAD

**Issue by csanyipal** [danap/ajqvue#2]
Hello,

I just started to use Ajqvue.
I am using it to continue developing my SQLite database.
I created the database with sqlite3 cli.
I can connect to the database, can view datas of tables but not for all tables.
I have seven tables in the database and can't view data of just two tables out there.
When I select such a table, I get a message box with the following messages:
**TableTabPanel_SQLite loadTable()
SQLException: Error parsing time stamp
SQLState: null, VendorError: 0**

In the sqlite3 cli I can SELECT that table without any problem to see it's datas. This table has 360 records out there.

The other problematic table has just two records.
When I select it in Ajqvue, I get the same error message as above.

So what is the problem in Ajqvue when want to select these two tables?

Best, Pali

**Comment by danap** [comment]
Hello Pali,

Please perfom the following or provide the schema for your two tables. With Ajqvue
you can do this via,

Edit | Preferences
Preferences | SQL
Check Table Structure, Uncheck Table Data

Data | Export | Table or Database.

I will review for an issue with Ajqvue, but as I warned the sqlite-jdbc has issues
with temporal data, timestamps, date, etc. The problem arises because a SQLite
database does not have a TIMESTAMP data type. It has TEXT, and REAL that
represent that data. Please see:

https://github.com/xerial/sqlite-jdbc/issues/88

danap.

**Comment by danap** [comment]
Hello Pali,

I have duplicated the error when the database table holds a string for the
Keltezes DATE column. When you view the data in the database via the
command line tool, you have DATES as 2018-04-18 for example that are
Strings.

Date, Time, Datetime, Timestamps are represented in Java as Long 
integers. This is the reported issue with the sqlite-jdbc as reported by
myself and others, xerial/sqlite-jdbc#88.

This is the reason I no longer include the sqlite-jdbc with the application.

I have been thinking about this issue, and has fustrated me with the
sqlite-project for some time.

I will review Ajqvue to see if I come up with a way to address this
issue. The problem from a database user perspective can be solved
by not using temporal data types that SQLite does not support.

This can be accomplished on deciding how you wish to represent
the Date column in the table definition, Integer or Text. I would assume
you wish Text. So for example in the following table definition below I have
changed the Date column, Keltezes, to CHAR(10). Now the data from your
database should be able to be pulled in from a csv or sql dump and Ajqvue
will work fine, but without the support of the Date calendar.

-- Ajqvue SQL Dump
-- Version: 1.15
-- WebSite: http://ajqvue.com
-- Host: localhost
-- Generated On: 2018.04.18 AD at 10:33:59 MDT
-- SQL version: SQLite 3.21.0
-- Database: /home/danap/sqlite-orak.db
--

-- ------------------------------------------

--
-- Table structure for table Orak
--

CREATE TABLE Orak2(
az INTEGER PRIMARY KEY UNIQUE,
Keltezes CHAR(10) DEFAULT NULL,
OrarendNapja TEXT DEFAULT NULL,
BlokkoraSzama TEXT DEFAULT NULL,
EvFolyam INTEGER DEFAULT NULL,
Tagozat TEXT DEFAULT NULL,
OraVazlat TEXT DEFAULT NULL,
OraNaplo TEXT DEFAULT NULL,
Emlekezteto TEXT DEFAULT NULL);
CREATE INDEX Orak_index2 ON Orak2(az);

I have added an issue item to my list of tasks and will keep
this issue open to remind me to review for a fix.

danap

**Comment by danap** [comment]
Hello Pali,

Seems that sqliteodbc is derived or from Werner. I believe this is the original
source of the sqlite-jdbc. Unfortunately the driver is not coded in Java. Ajqvue
is coded in Java.

danap.

**Comment by danap** [comment]
The project has addressed this issue to the best that is feasibly
possible with the v2.0 release. The main issue is with SQLite's
weak data type model.

Essential SQLite allows any of the four supported data types,
BLOB, TEXT, INTEGER, or REAL to be stored in a column. There are
some affinity rules that apply, but a table column in SQLite may
hold any combination of the supported data types.

So therefore SQL temporal types may be stored as strings, TEXT,
or numbers, INTEGER or REAL. A ResultSet that tries to retrieve
data via a getTime() for example with string content results in
a parsing error from the sqlite-jdbc.

Ajqvue has tried to deal with this by checking the table column's
SQL Type before retrieving data. This will only work if a table
column does not contain mixed data types.

Dana Proctor
Ajqvue Project Manager
